name = "todo-api"
main = "src/index.js"
compatibility_date = "2023-07-24"
usage_model = "bundled"

env = { }

[triggers]
crons = [ ]

[[ d1_databases ]]
binding = "DB"
database_name = "todo-api-prod"
database_id = "2971226e-6498-4603-a8fc-88fcfee005ea"